import type { 
  Profile, 
  Experience, 
  Project, 
  Skill, 
  Tool, 
  Certification, 
  Blog, 
  Testimonial, 
  Education,
  CustomTab,
  Message,
  DashboardStats
} from '@/types';

// Mock Profile
export const mockProfile: Profile = {
  id: '1',
  name: 'Tanveer Bakshi A',
  role: 'AI & Data Intelligence Analyst',
  tagline: 'Leveraging Headless Scraping & AI to transform healthcare data into intelligent insights.',
  experience: '7+ Years',
  location: 'Bengaluru, India',
  phone: '+91-9844999202',
  email: 'tanveerbakshii@gmail.com',
  linkedin: 'https://linkedin.com/in/tanveerbakshii',
  github: 'https://github.com/TanveerBakshii',
  bio: `AI & Data Intelligence Analyst with 7+ years of experience specializing in EMR/EHR systems and automated data acquisition. Expert in Headless Scraping (Playwright/Selenium) for legacy system integration and AI model training.\n\nCurrently bridging the gap between clinical workflows and advanced automation, I focus on identifying user challenges and translating them into high-fidelity data solutions.`,
  shortBio: 'AI & Data Intelligence Analyst with 7+ years experience. Expert in Headless Scraping & EMR Automation.',
  isPublic: true,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: new Date().toISOString(),
};

// Mock Experiences
export const mockExperiences: Experience[] = [
  {
    id: 'exp_1',
    company: 'Outlier (Remote)',
    title: 'AI Trainer (Freelance)',
    location: 'Remote',
    startDate: '2026-01-01',
    isCurrent: true,
    description: 'Contributing to AI model training through data annotation, response evaluation, and quality improvement tasks.',
    impact: [
      'Reviewing AI-generated outputs for accuracy, clarity, and contextual relevance',
      'Supporting prompt refinement and feedback loops to improve model performance',
      'Quality improvement of healthcare-specific AI responses',
    ],
    skills: ['AI Model Training', 'Data Annotation', 'Prompt Evaluation', 'NLP'],
    order: 1,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp_2',
    company: 'ClinicPro (Contract)',
    title: 'AI System Integrator & Data Integration Specialist',
    location: 'Bengaluru, India',
    startDate: '2026-01-01',
    isCurrent: true,
    description: 'Working on AI-driven healthcare workflows and system integrations across CRM and backend platforms.',
    impact: [
      'Monitoring system performance and identifying workflow gaps impacting usability',
      'Documenting workflows, system behavior, and integration processes',
      'Troubleshooting and improving system reliability across healthcare operations',
    ],
    skills: ['AI Integration', 'CRM', 'Workflow Mapping', 'Data Integration'],
    order: 2,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp_3',
    company: 'ABK Software Services Pvt. Ltd.',
    title: 'Quality Assurance & Application Support Specialist / Business Analyst',
    location: 'Bengaluru, India',
    startDate: '2023-12-01',
    endDate: '2026-01-01',
    isCurrent: false,
    description: 'Conducted UAT testing simulating real-world clinical workflows across hospital ERP systems.',
    impact: [
      'Designed and executed 200+ test scenarios per project reflecting actual user interactions',
      'Identified usability issues and workflow gaps during testing shared with stakeholders',
      'Documented RCA and functional documentation for system inefficiencies',
    ],
    skills: ['UAT Testing', 'ERP', 'Business Analysis', 'QA', 'Documentation'],
    order: 3,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp_4',
    company: 'Practo Technologies Pvt. Ltd.',
    title: 'Senior Support Analyst – EMR Systems',
    location: 'Bengaluru, India',
    startDate: '2022-05-01',
    endDate: '2023-11-30',
    isCurrent: false,
    description: 'Provided L1/L2/L3 support for EMR systems across 500+ clinics.',
    impact: [
      'Identified recurring system issues affecting clinical and billing workflows',
      'Performed root cause analysis to identify underlying system and usability gaps',
      'Maintained 99% SLA compliance for critical data issues',
    ],
    skills: ['EMR', 'L3 Support', 'RCA', 'SLA Management', 'Clinical Workflows'],
    order: 4,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp_5',
    company: 'Rajshekar Multi-Speciality Hospital',
    title: 'Digital Medical Records Analyst',
    location: 'Bengaluru, India',
    startDate: '2017-09-01',
    endDate: '2022-01-31',
    isCurrent: false,
    description: 'Analyzed hospital workflows across registration, billing, and clinical documentation.',
    impact: [
      'Supported improvements in operational processes and EMR adoption',
      'Ensured data accuracy during system usage and migration',
      'Trained staff across departments on digital record systems',
    ],
    skills: ['Workflow Analysis', 'Medical Records', 'EMR Adoption', 'Data Accuracy'],
    order: 5,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp_6',
    company: 'BGS GMS Hospital',
    title: 'Medical Records Technician',
    location: 'Bengaluru, India',
    startDate: '2012-12-01',
    endDate: '2014-08-31',
    isCurrent: false,
    description: 'Maintained and validated patient medical records and documentation.',
    impact: [
      'Identified data entry issues and supported process improvements',
      'Validated record compliance with hospital standards',
    ],
    skills: ['Medical Records', 'Data Validation', 'Documentation'],
    order: 6,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
];


// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'project_headless_scraper',
    title: 'Headless EMR Scraper & Aggregator',
    slug: 'headless-emr-scraper',
    summary: 'Automated data extraction system for legacy EMRs without native API support.',
    description: 'Developed a high-performance scraping engine using Playwright and Python to aggregate clinical data from legacy health systems.',
    challenge: 'Crucial clinical data was trapped in EMR systems lacking modern FHIR or REST APIs.',
    solution: 'Built a resilient headless scraping architecture that navigates complex EMR UIs to extract structured JSON data.',
    outcome: 'Automated data acquisition for 15+ legacy systems, saving 40+ manual labor hours weekly.',
    metrics: [
      { label: 'Scraping Rate', value: '2.5M+', icon: 'Database' },
      { label: 'Data Accuracy', value: '99.8%', icon: 'CheckCircle' },
      { label: 'Time Saved', value: '40h/wk', icon: 'Clock' },
      { label: 'Success Rate', value: '98.6%', icon: 'TrendingUp' },
    ],
    technologies: ['Python', 'Playwright', 'Selenium', 'PostgreSQL', 'Docker'],
    skills: ['Headless Scraping', 'Data Engineering', 'EMR Automation', 'ETL'],
    images: [],
    featured: true,
    order: 0,
    isPublic: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '1',
    title: 'RCM Performance Dashboard',
    slug: 'rcm-performance-dashboard',
    summary: 'Comprehensive revenue cycle management dashboard with real-time KPIs.',
    description: 'Built a comprehensive RCM dashboard that provides real-time visibility into revenue cycle performance.',
    challenge: 'Healthcare organization struggled with fragmented revenue data across multiple systems.',
    solution: 'Integrated data from Epic, billing systems, and payer portals into a unified Power BI dashboard.',
    outcome: 'Reduced days in AR by 15%, improved clean claim rate to 94%, and saved 25 hours per week.',
    metrics: [
      { label: 'Clean Claim Rate', value: '94%', icon: 'TrendingUp' },
      { label: 'Days in AR', value: '32', icon: 'Clock' },
      { label: 'Time Saved', value: '25h/wk', icon: 'Users' },
      { label: 'Impact', value: '$2.3M', icon: 'DollarSign' },
    ],
    technologies: ['Power BI', 'SQL', 'Epic', 'Python', 'Azure'],
    skills: ['Data Visualization', 'ETL', 'Healthcare Analytics', 'RCM'],
    images: [],
    featured: true,
    order: 1,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'FHIR Data Quality Monitor',
    slug: 'fhir-data-quality-monitor',
    summary: 'Real-time FHIR data quality monitoring and validation system.',
    description: 'Developed a monitoring system that validates FHIR data exchange between healthcare systems.',
    challenge: 'Data quality issues in FHIR exchanges were causing integration failures.',
    solution: 'Built an automated validation engine with real-time alerts and data quality scoring.',
    outcome: 'Reduced integration failures by 78%, improved data quality score from 72% to 96%.',
    metrics: [
      { label: 'Data Quality', value: '96%', icon: 'TrendingUp' },
      { label: 'Failure Reduc.', value: '78%', icon: 'TrendingUp' },
      { label: 'Validation', value: '< 2 min', icon: 'Clock' },
      { label: 'Systems', value: '12', icon: 'Users' },
    ],
    technologies: ['FHIR', 'Python', 'PostgreSQL', 'React', 'Node.js'],
    skills: ['HL7/FHIR', 'Data Quality', 'API Integration', 'Full Stack'],
    images: [],
    featured: true,
    order: 2,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'AI-Assisted Chart Review',
    slug: 'ai-chart-review-triage',
    summary: 'ML-powered system for prioritizing medical chart reviews.',
    description: 'Implemented an AI-driven triage system that prioritizes chart reviews based on complexity and risk.',
    challenge: 'Manual chart review process was time-consuming and prone to missing high-risk cases.',
    solution: 'Deployed machine learning models to score and prioritize charts.',
    outcome: 'Increased review throughput by 45%, reduced turnaround time from 48 to 24 hours.',
    metrics: [
      { label: 'Throughput', value: '+45%', icon: 'TrendingUp' },
      { label: 'Turnaround', value: '24 hrs', icon: 'Clock' },
      { label: 'Accuracy', value: '92%', icon: 'TrendingUp' },
      { label: 'Cases', value: '50K+', icon: 'Users' },
    ],
    technologies: ['Python', 'TensorFlow', 'SQL', 'Power BI', 'GCP'],
    skills: ['Machine Learning', 'Healthcare AI', 'Data Science', 'Automation'],
    images: [],
    featured: true,
    order: 3,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Skills
export const mockSkills: Skill[] = [
  { id: '1', name: 'EMR/EHR', category: 'HEALTHCARE', proficiency: 95, description: 'Epic, Cerner, Practo, HIS', order: 1, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'UAT Testing', category: 'DATA_REPORTING', proficiency: 92, description: 'Workflow mapping, scenario design', order: 2, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Workflow Analysis', category: 'HEALTHCARE', proficiency: 90, description: 'Clinical & Operational workflows', order: 3, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'AI Model Training', category: 'ENGINEERING', proficiency: 85, description: 'Data annotation, Prompt evaluation', order: 4, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '5', name: 'Incident Analysis (RCA)', category: 'COLLABORATION', proficiency: 90, description: 'Problem solving for production support', order: 5, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '6', name: 'Power BI / Tableau', category: 'DATA_REPORTING', proficiency: 88, description: 'Dashboard visualization', order: 6, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '7', name: 'HL7/FHIR Basics', category: 'HEALTHCARE', proficiency: 80, description: 'Interoperability standards', order: 7, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '8', name: 'SQL & Excel', category: 'TOOLS', proficiency: 85, description: 'Data extraction & manipulation', order: 8, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '9', name: 'Headless Scraping', category: 'TOOLS', proficiency: 88, description: 'Automated data extraction using Playwright & Selenium', order: 9, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

// Mock Tools
export const mockTools: Tool[] = [
  { id: '1', name: 'Epic Systems', category: 'EMR', description: 'Certified Clarity, Hyperspace', order: 1, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Cerner', category: 'EMR', description: 'PowerChart, Millennium', order: 2, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Practo EMR', category: 'EMR', description: 'Clinical & Billing modules', order: 3, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'Power BI', category: 'Analytics', description: 'Visualization', order: 4, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '5', name: 'Tableau', category: 'Analytics', description: 'Data mining', order: 5, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '6', name: 'SQL Server', category: 'Database', description: 'Advanced queries', order: 6, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '7', name: 'Python', category: 'Engineering', description: 'Automation & AI', order: 7, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '8', name: 'Playwright', category: 'Scraping', description: 'Headless automation', order: 8, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '9', name: 'Selenium', category: 'Scraping', description: 'Legacy automation', order: 9, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '10', name: 'JIRA', category: 'Management', description: 'Issue tracking', order: 10, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '11', name: 'Azure', category: 'Cloud', description: 'Cloud infrastructure', order: 11, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '12', name: 'GCP', category: 'Cloud', description: 'Google Cloud Platform', order: 12, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

// Mock Technical Tags
export const mockTags: string[] = [
  'SQL', 'Power BI', 'Tableau', 'Excel', 'Python', 'HL7', 'FHIR', 'GCP', 
  'JIRA', 'Epic', 'Cerner', 'RCM', 'Playwright', 'Puppeteer', 'PostgreSQL', 
  'Docker', 'Azure', 'Selenium', 'EMR', 'EHR', 'UAT Testing', 'NLP', 'ETL'
];

// Mock Certifications
export const mockCertifications: Certification[] = [
  { id: '1', name: 'Clinical Data Management (CDM)', issuer: 'Industry Standard', order: 1, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Medical Coding – U.S. Healthcare', issuer: 'Industry Standard', order: 2, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Business Analysis Fundamentals', issuer: 'Industry Standard', order: 3, isPublic: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

// Mock Blogs
export const mockBlogs: Blog[] = [
  {
    id: 'blog_scraping',
    title: 'The Power of Headless Scraping in Healthcare',
    slug: 'headless-scraping-healthcare',
    excerpt: 'Why automated data extraction is the missing link in legacy EMR interoperability and AI model training.',
    content: '# Headless Scraping in Healthcare\n\nLegacy system integration remains the biggest hurdle in digital health...',
    tags: ['Headless Scraping', 'EMR', 'Automation', 'Interoperability'],
    readTime: 6,
    featured: true,
    isPublic: true,
    views: 450,
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '1',
    title: 'Optimizing EMR Workflows for Clinicians',
    slug: 'optimizing-emr-workflows',
    excerpt: 'Key strategies for reducing burnout through better EMR design.',
    content: '# Optimizing EMR Workflows\n\nEMR systems are often a source of frustration...',
    tags: ['EMR', 'UX', 'Healthcare IT'],
    readTime: 5,
    featured: true,
    isPublic: true,
    views: 120,
    publishedAt: '2024-01-15T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Clinical Operations Lead',
    role: 'Healthcare Manager',
    company: 'Leading Hospital',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face',
    quote: "Tanveer's ability to bridge the gap between clinical needs and technical implementation saved us months of rework during our EMR upgrade.",
    order: 1,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Education
export const mockEducation: Education[] = [
  {
    id: '1',
    institution: 'Jain (Deemed-to-be University)',
    degree: 'MBA',
    field: 'Healthcare Management',
    startDate: '2024-06-01',
    isCurrent: true,
    description: 'Pursuing MBA in Healthcare Management to bridge clinical experience with healthcare administration.',
    order: 1,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    institution: 'Padmashree College of MRT (RGUHS)',
    degree: 'B.Sc.',
    field: 'Medical Record Technology',
    startDate: '2018-09-01',
    endDate: '2021-10-15',
    isCurrent: false,
    description: 'Degree in Medical Record Technology focusing on health information management and coding.',
    order: 2,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    institution: 'Bangalore Medical College & Research Institute',
    degree: 'Diploma',
    field: 'Medical Record Technology (DMRT)',
    startDate: '2015-08-01',
    endDate: '2017-06-30',
    isCurrent: false,
    description: 'Fundamentals of medical record management and clinical documentation.',
    order: 3,
    isPublic: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },

];

// Mock Custom Tabs
export const mockCustomTabs: CustomTab[] = [
  {
    id: '1',
    title: 'API Playground',
    slug: 'api-playground',
    description: 'Interactive API documentation and testing',
    content: '# API Playground\n\nTest the portfolio API endpoints...',
    type: 'WIDGET',
    order: 1,
    isPublic: true,
    isVisible: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Live Projects',
    slug: 'live-projects',
    description: 'Real-time project monitoring and status',
    content: '# Live Projects\n\nCurrent project statuses...',
    type: 'WIDGET',
    order: 2,
    isPublic: true,
    isVisible: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalViews: 12543,
  uniqueVisitors: 3421,
  pageViews: {
    '/': 5234,
    '/projects': 3421,
    '/skills': 2100,
    '/contact': 1788,
  },
  topProjects: [
    { id: '1', title: 'RCM Performance Dashboard', views: 892 },
    { id: '2', title: 'FHIR Data Quality Monitor', views: 756 },
    { id: '3', title: 'AI-Assisted Chart Review', views: 634 },
  ],
  recentMessages: [],
  resumeDownloads: 234,
};

// Mock Messages
export const mockMessages: Message[] = [];